// <auto-generated />
using System;
using FilmCollection.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FilmCollection.Migrations
{
    [DbContext(typeof(FilmCollectionContext))]
    [Migration("20220203055558_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("FilmCollection.Models.Category", b =>
                {
                    b.Property<int>("category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category_name")
                        .HasColumnType("TEXT");

                    b.HasKey("category_id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            category_id = 1,
                            category_name = "Action/Adventure"
                        },
                        new
                        {
                            category_id = 2,
                            category_name = "Comedy"
                        },
                        new
                        {
                            category_id = 3,
                            category_name = "Drama"
                        },
                        new
                        {
                            category_id = 4,
                            category_name = "Family"
                        },
                        new
                        {
                            category_id = 5,
                            category_name = "Horror/Suspense"
                        },
                        new
                        {
                            category_id = 6,
                            category_name = "Miscellaneous"
                        },
                        new
                        {
                            category_id = 7,
                            category_name = "Television"
                        },
                        new
                        {
                            category_id = 8,
                            category_name = "VHS"
                        });
                });

            modelBuilder.Entity("FilmCollection.Models.NewMovie", b =>
                {
                    b.Property<int>("film_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("category_id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("category_id1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("director")
                        .HasColumnType("TEXT");

                    b.Property<bool>("edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lent_to")
                        .HasColumnType("TEXT");

                    b.Property<string>("notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<int>("year")
                        .HasColumnType("INTEGER");

                    b.HasKey("film_id");

                    b.HasIndex("category_id1");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            film_id = 1,
                            category_id = 1,
                            director = "John Doe",
                            edited = false,
                            lent_to = "",
                            notes = "",
                            rating = "PG-13",
                            title = "Casino Royale",
                            year = 2006
                        },
                        new
                        {
                            film_id = 2,
                            category_id = 1,
                            director = "John Doe",
                            edited = false,
                            lent_to = "",
                            notes = "",
                            rating = "PG-13",
                            title = "Skyfall",
                            year = 2013
                        },
                        new
                        {
                            film_id = 3,
                            category_id = 1,
                            director = "John Doe",
                            edited = false,
                            lent_to = "",
                            notes = "",
                            rating = "PG-13",
                            title = "No Time To Die",
                            year = 2021
                        });
                });

            modelBuilder.Entity("FilmCollection.Models.NewMovie", b =>
                {
                    b.HasOne("FilmCollection.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("category_id1");
                });
#pragma warning restore 612, 618
        }
    }
}
